### ISSUE TITLE
Potentially inaccurate extraction of domain

### ISSUE THREAD

**Issue by ducalpha** [dibollinger/CookieBlock-Crawler-Prototype#1]
The following line extracts `domain` as `c[1]`
https://github.com/dibollinger/CookieBlock-Crawler-Prototype/blob/801cb332cdcdddaea4e57e2ac2889653ed623071/src/cookiebot_scraper.py#L250

However, from Cookiebot's javascript [uc.js](https://consent.cookiebot.com/uc.js)'s function `this.resetCookies = function()`, `c[6]` may be more accurate. For example, from the `cc.js` code's `CookieConsentDialog.cookieTableNecessary`, the last field may contain more specific domain, including a subdomain, while the first field does not.

**Comment by ducalpha** [comment]
After reading `cc.js`, using the domain as `c[1]` may be an approximation of the cookie's domain as it is used in `r = this.getProviderInfo(a[7], a[1]);`.

Furthermore, sometimes the value of `c[1]` may contain `<br/>` such as on `acm.org`: `["CookieConsent","acm.org<br/>awards.acm.org","Stores the user\'s cookie consent state for the current domain","1 year","HTTP","1","","cookiebot.com"]`. Therefore, it is necessary to split on `<br/>`

**Comment by dibollinger** [comment]
Did you mean `c[7]`? Because I'm pretty sure that the value of `c[6]` is a regex match for the cookie name `c[0]`, which in practice is often an empty string. I believe it is used for cookies where the declaration doesn't exactly match the name of the actual cookie, as the name itself contains a randomized string -- something that my script actually doesn't consider...  so that is definitely a possibility for improvement.

Here's an example of `c[6]` being used as a regex match in the wild, on `gamefly.com`:
```
["TS#","api.gamefly.com","Used to ensure website security and fraud detection.","Session","HTTP","1","^TS[0-9a-z_]{8}_*[0-9a-z]{0,4}$","www.gamefly.com"]
```

**Now for the domains:**

Your observation is correct in that `c[7]` also stores a domain, as does `c[1]`. However, I don't think `c[7]` is necessarily a better fit for matching the declaration to the observed cookies. This becomes apparent when visiting the website `gamefly.com`, which produced a `cc.js` file such as the following:

https://github.com/dibollinger/CookieBlock-Crawler-Prototype/blob/main/documentation/prototyping_cookiebot/example_dat/example2_cc.js

We find the following strictly necessary cookie:
```
["CookieConsent","gamefly.com","Stores the user's cookie consent state for the current domain","1 year","HTTP","1","","cookiebot.com"]
```
This is Cookiebot's consent cookie, which is set when the banner is clicked on. This is an instance of where `c[1]` and `c[7]` differ -- in many other instances these domains match. Now, while `c[7]` may be more accurate to the actual origin and purpose of the cookie, `c[1]` is a more accurate match for the domain string stored in the observed cookie.

Here is the data stored by the consent cookie:
```
CookieConsent:"
Value: {stamp:%27odEX9dWicTB2FYmyP434HgY3o8V+hF8Ji94SzHcaALduA83NcZTu7Q==%27%2Cnecessary:true%2Cpreferences:true%2Cstatistics:true%2Cmarketing:true%2Cver:1%2Cutc:1658950235691%2Cregion:%27de%27}"
Created:"Wed, 27 Jul 2022 19:30:35 GMT"
Domain:"www.gamefly.com"
Expires / Max-Age:"Thu, 27 Jul 2023 19:30:35 GMT"
HostOnly:true
HttpOnly:false
Last Accessed:"Wed, 27 Jul 2022 19:30:35 GMT"
Path:"/"
SameSite:"None"
Secure:true
Size:200
```
As such, the unique identifier for this cookie is `{ name="CookieConsent", domain="www.gamefly.com", path="/" }`, for which `c[1]` is the better match. Therefore, `c[7]` is not necessarily the better choice for matching cookie purpose to the observed cookie.

Secondly, both c[1] and c[7] may contain the linebreak element `<br/>`. This can be seen on `cc.js` extracted from the website `purplemath.com`:

https://github.com/dibollinger/CookieBlock-Crawler-Prototype/blob/main/documentation/prototyping_cookiebot/example_dat/example1_cc.js

```
["_gid","mathway.com<br/>purplemath.com","Registers a unique ID that is used to generate statistical data on how the visitor uses the website.","1 day","HTTP","1","","www.mathway.com<br/>www.purplemath.com"],
["px.gif","media.net<br/>s.mnet-ad.net","This cookie is used to determine if the visitor has any adblocker software in their browser – this information can be used to make website content inaccessible to visitors if the website is financed with third-party advertisement.","Session","Pixel","5","","contextual.media.net<br/>s.mnet-ad.net"]
```
Here we find the linebreak element in both `c[1]` and `c[7]`, even when they are not equivalent fields.

Moreover, the linebreak element is handled when matching the cookie declaration to the observed cookie, in the following script:

https://github.com/dibollinger/CookieBlock-Consent-Crawler/blob/d479dcd51064a3a647d5372cae157f909b6648a1/database_processing/extract_cookies_from_db.py#L239

Here I split the domains by the element if it exists, and treat each domain as valid. We try each domain until we find a match.

As such, I will close the issue, since I believe no changes are necessary for the data collection here.
I may update the cookie name extraction to consider the regex, but this would happen in the other repositories.
